### ISSUE TITLE
Unable to find suitable version for Polymer

### ISSUE THREAD

**Issue by justindra** [ecwyne/meteor-voice-elements#2]
Hi,

After adding this package and then execution meteor, I'm receiving this error:

```
 installing voice-elements into public direcory...
W20150224-10:32:43.816(11)? (STDERR)          
W20150224-10:32:43.816(11)? (STDERR) /home/user/.meteor/packages/meteor-tool/.1.0.40.jw8xkf++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:206
W20150224-10:32:43.816(11)? (STDERR)                            throw(ex);
W20150224-10:32:43.816(11)? (STDERR)                                  ^
W20150224-10:32:43.836(11)? (STDERR) polymer: Unable to find suitable version for polymer
W20150224-10:32:43.836(11)? (STDERR)     at Object.Future.wait (/home/jared/.meteor/packages/meteor-tool/.1.0.40.jw8xkf++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:326:15)
W20150224-10:32:43.836(11)? (STDERR)     at Object.install (packages/meteor/helpers.js:119:1)
W20150224-10:32:43.836(11)? (STDERR)     at Package (packages/ecwyne:voice-elements/voice-elements.js:25:1)
W20150224-10:32:43.836(11)? (STDERR)     at /home/jared/MeteorApps/competitionapp/.meteor/local/build/programs/server/packages/ecwyne_voice-elements.js:47:4
W20150224-10:32:43.836(11)? (STDERR)     at /home/jared/MeteorApps/competitionapp/.meteor/local/build/programs/server/packages/ecwyne_voice-elements.js:54:3
W20150224-10:32:43.836(11)? (STDERR)     at /home/jared/MeteorApps/competitionapp/.meteor/local/build/programs/server/boot.js:205:10
W20150224-10:32:43.837(11)? (STDERR)     at Array.forEach (native)
W20150224-10:32:43.837(11)? (STDERR)     at Function._.each._.forEach (/home/jared/.meteor/packages/meteor-tool/.1.0.40.jw8xkf++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150224-10:32:43.837(11)? (STDERR)     at /home/jared/MeteorApps/competitionapp/.meteor/local/build/programs/server/boot.js:116:5
W20150224-10:32:43.837(11)? (STDERR)     - - - - -
W20150224-10:32:43.837(11)? (STDERR)     at createError (/home/jared/.meteor/packages/ecwyne_voice-elements/.1.0.2.jxwv6d++os+web.browser+web.cordova/npm/node_modules/bower/lib/util/createError.js:4:15)
W20150224-10:32:43.837(11)? (STDERR)     at Manager._electSuitable (/home/jared/.meteor/packages/ecwyne_voice-elements/.1.0.2.jxwv6d++os+web.browser+web.cordova/npm/node_modules/bower/lib/core/Manager.js:763:15)
W20150224-10:32:43.837(11)? (STDERR)     at /home/jared/.meteor/packages/ecwyne_voice-elements/.1.0.2.jxwv6d++os+web.browser+web.cordova/npm/node_modules/bower/lib/core/Manager.js:558:25
W20150224-10:32:43.837(11)? (STDERR)     at _fulfilled (/home/jared/.meteor/packages/ecwyne_voice-elements/.1.0.2.jxwv6d++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:787:54)
W20150224-10:32:43.837(11)? (STDERR)     at self.promiseDispatch.done (/home/jared/.meteor/packages/ecwyne_voice-elements/.1.0.2.jxwv6d++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:816:30)
W20150224-10:32:43.837(11)? (STDERR)     at Promise.promise.promiseDispatch (/home/jared/.meteor/packages/ecwyne_voice-elements/.1.0.2.jxwv6d++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:749:13)
W20150224-10:32:43.837(11)? (STDERR)     at /home/jared/.meteor/packages/ecwyne_voice-elements/.1.0.2.jxwv6d++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:810:14
W20150224-10:32:43.838(11)? (STDERR)     at flush (/home/jared/.meteor/packages/ecwyne_voice-elements/.1.0.2.jxwv6d++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:108:17)
W20150224-10:32:43.838(11)? (STDERR)     at process._tickDomainCallback (node.js:463:13)                                      
```

Just wondering if there was something I would need to do. I've added both `ecwyne:ploymer` and `ecwyne:polymer-elements` separately and it doesn't seem to help.

**Comment by ghost** [comment]
I had this problem with boxxa:meteor-polymer-elements. I completely removed public/bower_components directory and re-run the meteor app. Seemed to help. I think there was something stale in the bower_components directory which prevented the polymer package from installing cleanly.

**Comment by justindra** [comment]
I've tried that and the error still occurs. It doesn't seem to help with much.
